### PR TITLE
Fix indicate same id bug when mutiple faces in frame

### PR DESCRIPTION
**Pull request by youngjae-avikus**
**Recognize thread bug when multiple faces are in frame**

Hello
It's recognized in a video with multiple faces in one frame, but individual face IDs come out the same, so I felt something was wrong. When I looked at the code, the `thread.join` part was missing, so I don't think the semaphore of global variables is guaranteed. So it can be solved by adding `thread.join`, but is it possible to modify it to a more general code?

### CODE REVIEW

**Comment by TruongVanPhuoc** [comment]
Tôi đã thử và thấy tốc độ khung hình giảm rất nhiều, bạn có thể thay đổi điều đó nhanh hơn không ?

**Comment by TruongVanPhuoc** [comment]
I have tried and found the frame rate drop a lot, can you change that to be faster?

**Comment by vectornguyen76** [comment]
@TruongVanPhuoc  yes, I try to improve FPS, but it has some problems

**Comment by youngjae-avikus** [comment]
I'll take a look, too

**Comment by youngjae-avikus** [comment]
Is it possible to share if there is an advanced part?

**Comment by vectornguyen76** [comment]
@youngjae-avikus  This is all.

**Pull request closed without merging**
